### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by lucy0701** [lucy0701/Mongbit_FE#2]
**services**
- [ ] api관련 코드 분리

**hooks**
- useCallBack 활용: 학습 필요
- [ ] like, comment, share, link copy -> test 시작, 결과 페이지에서 모두 필요
- [ ] test, user : Data 재사용 가장 많음 훅으로 처리

**constant**
- [ ] 파일 분리

**image, loading**
- [ ] next : 이미지 최적화
- [ ] loading
